
cc_binary(
    name = "1brc",
    srcs = ["CalculateAverage_KrishnaMandal.cpp"],
    copts = ["-std=c++17"],
    data = ["//:measurement"],
)

# cc_binary(
#     name = "sh_1brc",
#     srcs = ["CalculateAverage_KrishnaMandal.cpp"],
#     copts = ["-std=c++17"],
#     data = ["//:sh_measurement"],
# )

cc_binary(
    name = "jar_1brc",
    srcs = ["CalculateAverage_KrishnaMandal.cpp"],
    copts = ["-std=c++17"],
    data = ["//:jar_measurement"],
)

cc_binary(
    name = "cr_1brc",
    srcs = ["CalculateAverage_KrishnaMandal.cpp"],
    copts = ["-std=c++17"],
    data = ["//:rule_measurement"],
)
